name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  describe:
    runs-on: ubuntu-latest
    steps:
      - name: Install frictionless
        run: pip install frictionless
      - name: Describe
        run: frictionless describe https://raw.githubusercontent.com/datonic/atmospheric-carbon-dioxide-trends/main/datapackage.yaml --stats
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install frictionless
        run: pip install frictionless
      - name: Describe
        run: frictionless extract https://raw.githubusercontent.com/datonic/atmospheric-carbon-dioxide-trends/main/datapackage.yaml --csv > dataset.csv
      - name: Upload to IPFS
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: "dataset.csv"
      - name: Replace archive_cid
        run: >
          sed -i "s/archive_cid: .*/archive_cid: ${{ steps.web3.outputs.cid }}/g" datapackage.yaml
