name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  describe:
    runs-on: ubuntu-latest
    steps:
      - name: Install frictionless
        run: pip install frictionless
      - name: Describe
        run: frictionless describe https://raw.githubusercontent.com/datonic/atmospheric-carbon-dioxide-trends/main/datapackage.yaml --stats
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install frictionless
        run: pip install frictionless
      - name: Describe
        run: frictionless extract https://raw.githubusercontent.com/datonic/atmospheric-carbon-dioxide-trends/main/datapackage.yaml --csv > dataset.csv
      - name: Upload to IPFS
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: "dataset.csv"
      - name: Replace archiveCID
        run: |
          sed -i "s/archiveCID: .*/archiveCID: ${{ steps.web3.outputs.cid }}/g" datapackage.yaml
      - name: Replace IPFS CID
        run: |
          sed -E -i "s|CID-[[:alnum:]]+|${{ steps.web3.outputs.cid }}|g" README.md
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@users.noreply.github.com"
          git add datapackage.yaml README.md
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "chore: :id: update CID"
            git push
          fi
